name: Swift Test Coverage
description: Automated code coverage reporting for Swift packages
author: oleksiikolomiiets

branding:
  icon: shield
  color: green

tags:
  - swift
  - coverage
  - testing
  - code-quality
  - ci-cd
  - spm

inputs:
  # Basic configuration
  macos-version:
    description: 'macOS runner version (e.g., "latest", "15", "14")'
    required: false
    default: 'latest'
  xcode-version:
    description: 'Xcode version to use (default: system default)'
    required: false
    default: ''
  source-path-override:
    description: 'Override source path pattern (default: {PROJECT}/Sources)'
    required: false
    default: ''
  project-name-override:
    description: 'Override project name (default: repository name)'
    required: false
    default: ''
  coverage-comment-header:
    description: 'Header for coverage comment'
    required: false
    default: '### 🛡️ Code Coverage Report'
  working-directory:
    description: 'Working directory for Swift commands (default: repository root)'
    required: false
    default: '.'
  skip-label:
    description: 'Label name to skip workflow execution (default: skip-coverage)'
    required: false
    default: 'skip-coverage'

  # Multi-job combined comments
  post-comment:
    description: 'Post coverage comment to PR (set to false when using combined comments)'
    required: false
    default: 'true'
  job-name:
    description: 'Name/description for this coverage job (used in combined reports)'
    required: false
    default: ''

  # Coverage threshold
  coverage-threshold:
    description: 'Coverage threshold percentage (if set, enables quality indicators and Details section)'
    required: false
    default: ''
  fail-on-low-coverage:
    description: 'Fail the job if coverage is below threshold'
    required: false
    default: 'false'

outputs:
  coverage-percentage:
    description: 'The calculated coverage percentage'
    value: ${{ steps.extract.outputs.coverage }}
  coverage-table:
    description: 'The coverage table in markdown format'
    value: ${{ steps.extract.outputs.coverage-table }}
  job-name:
    description: 'The job name for this coverage run'
    value: ${{ inputs.job-name }}

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: List Xcode installations
      shell: bash
      run: sudo ls -1 /Applications | grep "Xcode" || echo "No Xcode installations found"

    - name: Validate Xcode version
      if: inputs.xcode-version != ''
      shell: bash
      run: |
        REQUESTED_XCODE="Xcode_${{ inputs.xcode-version }}.app"
        if [ ! -d "/Applications/$REQUESTED_XCODE" ]; then
          echo "❌ Error: Xcode version ${{ inputs.xcode-version }} is not installed"
          echo ""
          echo "Available Xcode versions:"
          sudo ls -1 /Applications | grep "Xcode" | sed 's/Xcode_//g' | sed 's/.app//g' | sed 's/^/  - /'
          echo ""
          echo "Please update your workflow to use one of the available versions."
          exit 1
        fi
        echo "✅ Xcode ${{ inputs.xcode-version }} is available"

    - name: Select Xcode version
      if: inputs.xcode-version != ''
      shell: bash
      run: |
        XCODE_PATH="/Applications/Xcode_${{ inputs.xcode-version }}.app/Contents/Developer"
        sudo xcode-select -s "$XCODE_PATH"

    - name: Verify Swift Version
      shell: bash
      run: swift --version

    - name: Run Swift Tests with Coverage
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        swift test --enable-swift-testing --enable-code-coverage
        CODECOV_PATH=$(swift test --enable-swift-testing --enable-code-coverage --show-codecov-path)
        echo "CODECOV_PATH=$CODECOV_PATH" >> $GITHUB_ENV

    - name: Process Coverage Data
      id: extract
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        set -euo pipefail

        # ============================================================================
        # Helper Functions
        # ============================================================================

        show_error_and_exit() {
          local error_msg="$1"
          local exit_code="${2:-1}"
          echo "::error title=Coverage Processing Error::$error_msg"
          exit "$exit_code"
        }

        validate_dependencies() {
          local missing_deps=()

          if ! command -v jq >/dev/null 2>&1; then
            missing_deps+=("jq")
          fi

          if ! command -v bc >/dev/null 2>&1; then
            missing_deps+=("bc")
          fi

          if ! command -v awk >/dev/null 2>&1; then
            missing_deps+=("awk")
          fi

          if [ ${#missing_deps[@]} -gt 0 ]; then
            show_error_and_exit "Missing required dependencies: ${missing_deps[*]}"
          fi
        }

        validate_coverage_data() {
          local codecov_path="$1"

          if [ ! -f "$codecov_path" ]; then
            show_error_and_exit "Coverage file not found: $codecov_path"
          fi

          if [ ! -r "$codecov_path" ]; then
            show_error_and_exit "Coverage file is not readable: $codecov_path"
          fi

          if ! jq -e '.data[0].files' "$codecov_path" >/dev/null 2>&1; then
            show_error_and_exit "Invalid coverage JSON structure in: $codecov_path"
          fi

          echo "✅ Coverage data validated: $codecov_path"
        }

        extract_target_from_path() {
          local filename="$1"
          local project_name="$2"
          local target_name=""

          if echo "$filename" | grep -q '/Sources/[^/]*/'; then
            target_name=$(echo "$filename" | sed -E 's|.*/Sources/([^/]+)/.*|\1|')
          elif echo "$filename" | grep -q '/Sources/[^/]*\.swift$'; then
            target_name=$(echo "$filename" | sed -E 's|.*/Sources/([^/]*)\.swift$|\1|')
          else
            target_name="$project_name"
          fi

          echo "$target_name"
        }

        calculate_coverage_percentage() {
          local total_lines="$1"
          local covered_lines="$2"
          local coverage=0

          if [ "$total_lines" -gt 0 ]; then
            coverage=$(echo "scale=6; $covered_lines * 100 / $total_lines" | bc)
          fi

          echo "$coverage"
        }

        round_coverage() {
          local coverage="$1"
          echo "$coverage" | awk '{print int($1 * 100 + 0.5) / 100}'
        }

        create_temp_file() {
          local purpose="$1"
          local temp_file

          temp_file=$(mktemp) || show_error_and_exit "Failed to create temporary file for: $purpose"
          echo "$temp_file"
        }

        cleanup_temp_files() {
          local files=("$@")
          for file in "${files[@]}"; do
            if [ -n "$file" ] && [ -f "$file" ]; then
              rm -f "$file"
            fi
          done
        }

        generate_table_row() {
          local row_number="$1"
          local target_name="$2"
          local total_lines="$3"
          local coverage_percentage="$4"

          echo "| $row_number | $target_name | $total_lines | **${coverage_percentage}%** |"
        }

        determine_coverage_header() {
          local average_coverage="$1"
          local threshold="$2"
          local show_quality="$3"

          local coverage_header="Coverage"

          if [ "$show_quality" = "true" ] && [ -n "$threshold" ]; then
            local coverage_int=$(echo "$average_coverage" | awk '{print int($1)}')
            if [ "$coverage_int" -lt "$threshold" ]; then
              coverage_header="⚠️"
            else
              coverage_header="✅"
            fi
          fi

          echo "$coverage_header"
        }

        # ============================================================================
        # Setup and Validation
        # ============================================================================

        # Setup temp file cleanup trap
        TEMP_FILES=()
        trap 'cleanup_temp_files "${TEMP_FILES[@]}"' EXIT

        # Set project name and source path
        PROJECT_NAME="${{ inputs.project-name-override }}"
        if [ -z "$PROJECT_NAME" ]; then
          PROJECT_NAME="${{ github.event.repository.name }}"
        fi

        SOURCE_PATH="${{ inputs.source-path-override }}"
        if [ -z "$SOURCE_PATH" ]; then
          SOURCE_PATH="${PROJECT_NAME}/Sources"
        fi

        # Validate dependencies and coverage data
        validate_dependencies
        validate_coverage_data "$CODECOV_PATH"

        # Validate required variables
        if [ -z "$PROJECT_NAME" ]; then
          show_error_and_exit "PROJECT_NAME is not set"
        fi

        # Initialize threshold
        THRESHOLD="${{ inputs.coverage-threshold }}"
        if [ -n "$THRESHOLD" ]; then
          show_quality="true"
        else
          show_quality="false"
        fi

        # Set coverage summary file path
        COVERAGE_SUMMARY_FILE="${{ github.workspace }}/coverage_summary.txt"

        # ============================================================================
        # Extract Coverage Data
        # ============================================================================

        # Check if there are any actual source files to report on
        if ! SOURCE_FILE_COUNT=$(jq -r '.data[0].files[] | select(.filename | test("/\\.build/") | not) | select(.filename | test("\\.swift$")) | select(.filename | test("/(Tests?|test)/") | not) | .filename' "$CODECOV_PATH" 2>&1 | wc -l); then
          show_error_and_exit "Failed to extract source files from coverage data"
        fi

        if [ "$SOURCE_FILE_COUNT" -eq 0 ]; then
          ALL_FILES="$PROJECT_NAME|0|0"
        else
          if ! ALL_FILES=$(jq -r '.data[0].files[] | select(.filename | test("/\\.build/") | not) | select(.filename | test("\\.swift$")) | select(.filename | test("/(Tests?|test)/") | not) | "\(.filename)|\(.summary.lines.count)|\(.summary.lines.covered)"' "$CODECOV_PATH" 2>&1); then
            show_error_and_exit "Failed to extract file coverage data"
          fi
        fi

        # ============================================================================
        # Process Coverage by Target
        # ============================================================================

        # Create temporary files
        TARGETS_DATA=$(create_temp_file "targets_data")
        TABLE_BODY=$(create_temp_file "table_body")
        COVERAGE_VALUES_FILE=$(create_temp_file "coverage_values")
        TEMP_FILES+=("$TARGETS_DATA" "$TABLE_BODY" "$COVERAGE_VALUES_FILE")

        # Parse files and group by target
        while IFS='|' read -r filename total_lines covered_lines; do
          if [ -n "$filename" ]; then
            target_name=$(extract_target_from_path "$filename" "$PROJECT_NAME")

            # Skip if target name looks like a test
            if echo "$target_name" | grep -qi test; then
              continue
            fi

            echo "$target_name|$total_lines|$covered_lines" >> "$TARGETS_DATA"
          fi
        done <<< "$ALL_FILES"

        # Aggregate data by target
        AGGREGATED_DATA=$(create_temp_file "aggregated_data")
        TEMP_FILES+=("$AGGREGATED_DATA")

        if [ -s "$TARGETS_DATA" ]; then
          if ! sort "$TARGETS_DATA" | awk -F'|' '
          {
            target = $1
            total_lines[target] += $2
            covered_lines[target] += $3
          }
          END {
            for (target in total_lines) {
              print target "|" total_lines[target] "|" covered_lines[target]
            }
          }' > "$AGGREGATED_DATA"; then
            show_error_and_exit "Failed to aggregate coverage data by target"
          fi
        fi

        # ============================================================================
        # Generate Coverage Table
        # ============================================================================

        target_counter=1
        total_lines_sum=0

        if [ -s "$AGGREGATED_DATA" ]; then
          while IFS='|' read -r target_name total_lines covered_lines; do
            if [ -n "$target_name" ]; then
              target_coverage=$(calculate_coverage_percentage "$total_lines" "$covered_lines")
              target_coverage_rounded=$(round_coverage "$target_coverage")

              generate_table_row "$target_counter" "$target_name" "$total_lines" "$target_coverage_rounded" >> "$TABLE_BODY"

              echo "$target_coverage" >> "$COVERAGE_VALUES_FILE"
              total_lines_sum=$((total_lines_sum + total_lines))
              target_counter=$((target_counter + 1))
            fi
          done < <(sort "$AGGREGATED_DATA")
        else
          generate_table_row "1" "$PROJECT_NAME" "0" "0" >> "$TABLE_BODY"
        fi

        # ============================================================================
        # Calculate Overall Coverage
        # ============================================================================

        if [ -f "$COVERAGE_VALUES_FILE" ]; then
          target_count=$(wc -l < "$COVERAGE_VALUES_FILE")
          if [ $target_count -gt 0 ]; then
            total_coverage_sum=$(awk '{sum+=$1} END {print sum}' "$COVERAGE_VALUES_FILE")
            average_coverage=$(echo "scale=6; $total_coverage_sum / $target_count" | bc)
          else
            average_coverage=0
          fi
        else
          average_coverage=0
          target_count=0
        fi

        average_coverage_rounded=$(round_coverage "$average_coverage")

        # ============================================================================
        # Generate Final Table
        # ============================================================================

        coverage_header=$(determine_coverage_header "$average_coverage_rounded" "$THRESHOLD" "$show_quality")

        # Write final table with header + body
        cat <<EOF > "$COVERAGE_SUMMARY_FILE"
        |   №  | Target | Lines | $coverage_header |
        |:----:|--------|------:|:---------:|
        EOF
        cat "$TABLE_BODY" >> "$COVERAGE_SUMMARY_FILE"

        # Add total row if multiple targets
        if [ $target_count -gt 1 ]; then
          echo "| | <p align=\"right\">**Total**</p> | $total_lines_sum | **${average_coverage_rounded}%** |" >> "$COVERAGE_SUMMARY_FILE"
        fi

        # ============================================================================
        # Set GitHub Actions Outputs
        # ============================================================================

        echo "coverage=$average_coverage_rounded" >> $GITHUB_OUTPUT

        echo "coverage-table<<EOF" >> $GITHUB_OUTPUT
        cat "$COVERAGE_SUMMARY_FILE" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

        if [ -n "$THRESHOLD" ]; then
          echo "threshold=$THRESHOLD" >> $GITHUB_OUTPUT
        else
          echo "threshold=" >> $GITHUB_OUTPUT
        fi

        # ============================================================================
        # Log Coverage Summary
        # ============================================================================

        echo ""
        echo "📊 Coverage Summary:"
        if [ -s "$AGGREGATED_DATA" ]; then
          while IFS='|' read -r target_name total_lines covered_lines; do
            if [ -n "$target_name" ]; then
              target_coverage=$(calculate_coverage_percentage "$total_lines" "$covered_lines")
              target_coverage_rounded=$(round_coverage "$target_coverage")
              echo "  • $target_name: ${target_coverage_rounded}%"
            fi
          done < <(sort "$AGGREGATED_DATA")
        fi
        echo "  Overall: ${average_coverage_rounded}%"
        if [ -n "$THRESHOLD" ]; then
          echo "  Threshold: ${THRESHOLD}%"
        fi
        echo ""

    - name: Comment on Pull Request
      if: github.event_name == 'pull_request' && inputs.post-comment == 'true'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');

          // Read coverage output from file
          const coverageOutput = fs.readFileSync('${{ github.workspace }}/coverage_summary.txt', 'utf8');

          // Create unique identifier using GitHub's job context
          const workflowName = '${{ github.workflow }}';
          const jobName = '${{ github.job }}';
          const customJobName = '${{ inputs.job-name }}';
          const jobId = customJobName || `${workflowName}:${jobName}`;
          const commentMarker = `<!-- swift-coverage-id: ${jobId} -->`;

          // Build threshold details if threshold provided
          const thresholdStr = '${{ steps.extract.outputs.threshold }}';
          const threshold = thresholdStr ? parseInt(thresholdStr, 10) : null;
          let thresholdSection = '';
          if (threshold !== null && threshold !== undefined) {
            thresholdSection = `
          <details>
          <summary><b>Details</b></summary>

          ### Threshold - ${threshold}%
            - ⚠️ below
            - ✅ meets

          </details>
          `;
          }

          const header = '${{ inputs.coverage-comment-header }}';
          const newComment = `
          ${header}

          ${coverageOutput}
          ${thresholdSection}
          _Generated by [Swift Coverage Action](https://github.com/oleksiikolomiietssnapp/swift-coverage-action)._
          ${commentMarker}
          `;

          // Fetch existing comments
          const comments = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.payload.pull_request.number,
          });

          // Identify and delete ONLY previous comments with the same job ID
          const botComments = comments.data.filter(comment =>
            comment.body.includes(commentMarker)
          );

          for (const botComment of botComments) {
            await github.rest.issues.deleteComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: botComment.id,
            });
          }

          // Create a comment on the pull request
          await github.rest.issues.createComment({
            issue_number: context.payload.pull_request.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: newComment,
          });

          console.log(`✅ Coverage comment posted successfully (ID: ${jobId})`);

    - name: Check Coverage Threshold
      if: inputs.fail-on-low-coverage == 'true' && inputs.coverage-threshold != ''
      shell: bash
      run: |
        COVERAGE=${{ steps.extract.outputs.coverage }}
        THRESHOLD="${{ inputs.coverage-threshold }}"

        echo "Coverage: ${COVERAGE}%"
        echo "Threshold: ${THRESHOLD}%"

        COVERAGE_INT=$(echo "$COVERAGE" | awk '{print int($1)}')

        if [ "$COVERAGE_INT" -lt "$THRESHOLD" ]; then
          echo "::error title=Coverage Below Threshold::Coverage ${COVERAGE}% is below the required threshold of ${THRESHOLD}%"
          exit 1
        else
          echo "✅ Coverage ${COVERAGE}% meets threshold ${THRESHOLD}%"
        fi
