# Minimal setup - just copy and go
# Copy to your repository's .github/workflows/ folder

name: Coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  coverage:
    uses: Snapp-Mobile/swift-coverage-action@v1.0.2
